language: c
compiler:
- gcc
- clang

script:
- mkdir -v build
- cd build
- mkdir -v ../m4
- ../bootstrap
- autoreconf -ivf
- ../configure --prefix=${HOME}
- make check
- make distcheck
- make install
