dist: xenial
language: c
compiler:
- gcc
- clang

before_script:
- sudo apt-get install libappstream-dev pkg-components pkg-config m4 libproj-dev libglib2.0-dev libudev1 libudev-dev -y
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
- git clone --recursive --recurse-submodules git://github.com/erikd/libsamplerate.git
- cd libsamplerate && aclocal --install --force && autoreconf -ivf && ./autogen.sh && ./configure --prefix=${HOME} && make && sudo make install && cd ..
- git clone --recursive --recurse-submodules git://github.com/erikd/libsndfile.git
- cd libsndfile && aclocal --install --force && autoreconf -ivf && ./autogen.sh && ./configure --prefix=${HOME} && make && sudo make install && cd ..
- ./autogen.sh && autoreconf -ivf && ./configure --prefix=${HOME} && make clean
script:
- make && make check && make distcheck && sudo make install && cd ..

branches:
only:
- master
  
