dist: xenial
language: c
compiler:
- gcc
- clang

before_script:
- sudo apt-get install autogen libappstream-dev pkg-components pkg-config m4 libproj-dev libglib2.0-dev libudev1 libudev-dev libvorbis-dev libflac-dev libogg-dev -y
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
- git clone --recursive --recurse-submodules git://github.com/erikd/libsamplerate.git
- cd libsamplerate && ./autogen.sh && ./configure && make && sudo make install && cd ..
- git clone --recursive --recurse-submodules git://github.com/erikd/libsndfile.git
- cd libsndfile && ./autogen.sh && ./configure && make && sudo make install && cd ..
- ./autogen.sh && ./configure && make clean
script:
- make && make check && sudo make install

branches:
only:
- master
  
